FROM eclipse-temurin:21-jdk-alpine
WORKDIR Eurekaworking/Dir/Eureka
COPY target/Eureka-Server-0.0.1-SNAPSHOT.jar /Eurekaworking/Dir/Eureka/Reservation-Eureka-Server.jar
CMD ["java","-jar","Reservation-Eureka-Server.jar"]